# Data cleaning

## Intro

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\santi\Documents\GitHub\Data Science Portfolio\Pizza Sales Dataset\pizza_sales.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pizza_id           48620 non-null  float64
 1   order_id           48620 non-null  float64
 2   pizza_name_id      48620 non-null  object
 3   quantity           48620 non-null  float64
 4   order_date         48620 non-null  object
 5   order_time         48620 non-null  object
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  object
 9   pizza_category     48620 non-null  object
 10  pizza_ingredients  48620 non-null  object
 11  pizza_name         48620 non-null  object
dtypes: float64(5), object(7)
memory usage: 4.5+ MB

In [4]:
df.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1.0,1.0,hawaiian_m,1.0,1/1/2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2.0,2.0,classic_dlx_m,1.0,1/1/2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3.0,2.0,five_cheese_l,1.0,1/1/2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4.0,2.0,ital_supr_l,1.0,1/1/2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5.0,2.0,mexicana_m,1.0,1/1/2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza

In [5]:
df['pizza_name'] = df['pizza_name'].str.replace('The ', '')

In [6]:
df.rename(columns={'pizza_name_id':'pizza_name_short', 'pizza_id':'n_pizza_sold'}, inplace=True)

In [7]:
df['pizza_size'] = df['pizza_size'].str.upper()

## Int values

In [8]:
print(df.dtypes)

n_pizza_sold         float64
order_id             float64
pizza_name_short      object
quantity             float64
order_date            object
order_time            object
unit_price           float64
total_price          float64
pizza_size            object
pizza_category        object
pizza_ingredients     object
pizza_name            object
dtype: object

In [9]:
fields_to_int = ['n_pizza_sold', 'order_id', 'quantity']

df[fields_to_int].info

<bound method DataFrame.info of        n_pizza_sold  order_id  quantity
0               1.0       1.0       1.0
1               2.0       2.0       1.0
2               3.0       2.0       1.0
3               4.0       2.0       1.0
4               5.0       2.0       1.0
...             ...       ...       ...
48615       48616.0   21348.0       1.0
48616       48617.0   21348.0       1.0
48617       48618.0   21348.0       1.0
48618       48619.0   21349.0       1.0
48619       48620.0   21350.0       1.0

[48620 rows x 3 columns]>

In [10]:
for col in fields_to_int:
    df[col] = df[col].astype(int)

print(df[fields_to_int].dtypes)

n_pizza_sold    int32
order_id        int32
quantity        int32
dtype: object

## Date values

In [11]:
df['order_date'].info

<bound method Series.info of 0          1/1/2015
1          1/1/2015
2          1/1/2015
3          1/1/2015
4          1/1/2015
            ...
48615    31-12-2015
48616    31-12-2015
48617    31-12-2015
48618    31-12-2015
48619    31-12-2015
Name: order_date, Length: 48620, dtype: object>

In [12]:
df['order_date'] = df['order_date'].str.replace('-', '/')
df['order_date'].str.match(r'^\d{2}/\d{2}/\d{4}$').value_counts()

order_date
True     30076
False    18544
Name: count, dtype: int64

In [13]:
df['order_date'][~df['order_date'].str.match(r'^\d{2}/\d{2}/\d{4}$')]

0         1/1/2015
1         1/1/2015
2         1/1/2015
3         1/1/2015
4         1/1/2015
           ...
46032    9/12/2015
46033    9/12/2015
46034    9/12/2015
46035    9/12/2015
46036    9/12/2015
Name: order_date, Length: 18544, dtype: object

In [14]:
df['order_date'].str.match(r'^\d{1}/\d{1}/\d{4}$').value_counts()[1]+ \
df['order_date'].str.match(r'^\d{1}/\d{2}/\d{4}$').value_counts()[1]+ \
df['order_date'].str.match(r'^\d{2}/\d{1}/\d{4}$').value_counts()[1]

C:\Users\santi\AppData\Local\Temp\ipykernel_6760\2542314569.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['order_date'].str.match(r'^\d{1}/\d{1}/\d{4}$').value_counts()[1]+ \
C:\Users\santi\AppData\Local\Temp\ipykernel_6760\2542314569.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['order_date'].str.match(r'^\d{1}/\d{2}/\d{4}$').value_counts()[1]+ \
C:\Users\santi\AppData\Local\Temp\ipykernel_6760\2542314569.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df['order_date'].str.match(r'^\d{2}/\d{1}/\d{4}$').value_counts()[1]

18544

So we have 4 different date format:
- dd/mm/yyyy
- d/mm/yyyy
- d/m/yyyy
- dd/m/yyyy

All of these can be handled properly by the 'to_datetime' funcion within the pandas package

In [15]:
df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True, errors='coerce').dt.date

In [16]:
df['order_date'].info

<bound method Series.info of 0        2015-01-01
1        2015-01-01
2        2015-01-01
3        2015-01-01
4        2015-01-01
            ...
48615    2015-12-31
48616    2015-12-31
48617    2015-12-31
48618    2015-12-31
48619    2015-12-31
Name: order_date, Length: 48620, dtype: object>

In [17]:
print(df['order_date'].isna().sum())
print(df['order_date'].dtypes)

0
object

## Time values

In [18]:
df['order_time'].str.match(r'^\d{2}:\d{2}:\d{2}$').value_counts()

order_time
True     48616
False        4
Name: count, dtype: int64

In [19]:
df['order_time'][~df['order_time'].str.match(r'^\d{2}:\d{2}:\d{2}$')]

43612    9:52:21
43613    9:52:21
43614    9:52:21
43615    9:52:21
Name: order_time, dtype: object

In [20]:
df['order_time'] = pd.to_datetime(df['order_time'], format='%H:%M:%S', errors='coerce').dt.time

In [21]:
df['order_time'].info

<bound method Series.info of 0        11:38:36
1        11:57:40
2        11:57:40
3        11:57:40
4        11:57:40
           ...
48615    21:23:10
48616    21:23:10
48617    21:23:10
48618    22:09:54
48619    23:02:05
Name: order_time, Length: 48620, dtype: object>

In [22]:
print(df['order_time'].isna().sum())
print(df['order_time'].dtypes)

0
object

## Table split

Create the sizes table

In [23]:
unique_sizes = df['pizza_size'].unique()

df_sizes = pd.DataFrame({
    'pizza_size': unique_sizes
})

size_to_n_people = {'S':2, 'M':4, 'L':8, 'XL':10, 'XXL':12}

df_sizes['size_to_n_people'] = df_sizes['pizza_size'].map(size_to_n_people)

df_sizes.sort_values('size_to_n_people', inplace=True)
df_sizes.insert(0, 'size_id', range(1, len(df_sizes)+1))
df_sizes.reset_index(drop=True, inplace=True)
df_sizes

   size_id pizza_size  size_to_n_people
0        1          S                 2
1        2          M                 4
2        3          L                 8
3        4         XL                10
4        5        XXL                12

Create the categories table

In [24]:
unique_category = df['pizza_category'].unique()

df_category = pd.DataFrame({
    'pizza_category': unique_category
})

df_category.insert(0, 'category_id', range(1, len(df_category)+1))
df_category.reset_index(drop=True, inplace=True)
df_category

   category_id pizza_category
0            1        Classic
1            2         Veggie
2            3        Supreme
3            4        Chicken

Create the pizzas table

In [25]:
df_pizza = df[['pizza_name', 'pizza_name_short', 'unit_price', 'pizza_ingredients',
               'pizza_size', 'pizza_category']]

df_pizza.drop_duplicates(inplace=True)
df_pizza.insert(0, 'pizza_id', range(1, len(df_pizza)+1))

C:\Users\santi\AppData\Local\Temp\ipykernel_6760\1750995371.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pizza.drop_duplicates(inplace=True)

In [26]:
df_pizza = df_pizza.merge(df_category[['pizza_category', 'category_id']],
                          on = 'pizza_category',
                          how='left')
df_pizza.drop(columns=['pizza_category'], inplace=True)

df_pizza = df_pizza.merge(df_sizes[['pizza_size', 'size_id']],
                          on = 'pizza_size',
                          how = 'left')
df_pizza.drop(columns=['pizza_size'], inplace=True)

Create the lines (one line per pizza pero order) table

In [27]:
df_line = df[['order_id', 'quantity', 'total_price', 'pizza_name_short']]
df_line.rename(columns={'total_price':'total_price_line'}, inplace=True)
df_line.insert(0, 'line_id', range(1, len(df_line)+1))
df_line.reset_index(drop=True, inplace=True)

C:\Users\santi\AppData\Local\Temp\ipykernel_6760\2982639382.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_line.rename(columns={'total_price':'total_price_line'}, inplace=True)

In [28]:
df_line = df_line.merge(df_pizza[['pizza_name_short', 'pizza_id']],
                        on = 'pizza_name_short',
                        how='left')
df_line.drop(columns=['pizza_name_short'], inplace=True)

Create the orders (each order can have more than one line) table

In [29]:
df_orders = df[['order_id', 'order_date', 'order_time']]
df_orders.drop_duplicates(inplace=True)
df_orders.reset_index(drop=True, inplace=True)

C:\Users\santi\AppData\Local\Temp\ipykernel_6760\1188468533.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_orders.drop_duplicates(inplace=True)

In [30]:
df_temp = pd.DataFrame(pd.merge(df_orders, df_line, on='order_id').groupby('order_id')['total_price_line'].sum())
df_temp.rename(columns={'total_price_line':'price_order'}, inplace=True)
df_temp.reset_index(inplace=True)

In [31]:
df_orders = df_orders.merge(df_temp[['order_id', 'price_order']],
                          on = 'order_id',
                          how = 'left')

# Database creation

In [ ]:
import pypyodbc as podbc

IF IT'S NECCESARY TO CREATE THE DATABASE, JUST CHANGE THE FOLLOWING CELL TO CODE TYPE AND RUN IT

In [ ]:
conn0 = podbc.connect("Driver={ODBC Driver 17 for SQL Server};"
                     "Server=ACER-SWIFT-3-SF\SQLEXPRESS01;"
                     "Database=master;"
                     "Trusted_Connection=yes;",
                     autocommit=True)


cursor0 = conn0.cursor()

cursor0.execute('CREATE DATABASE Pizza_sales_db')

cursor0.close()
conn0.close()

## Tables

We create another conenction variable due to the fact that we will now on work in the Pizza_sales_db database

In [34]:
conn = podbc.connect("Driver={ODBC Driver 17 for SQL Server};"
                     "Server=ACER-SWIFT-3-SF\SQLEXPRESS01;"
                     "Database=Pizza_sales_db;"
                     "Trusted_Connection=yes;",
                     autocommit=True)

In [35]:
cursor = conn.cursor()

In [36]:
cursor.execute("IF OBJECT_ID('Categories') IS NOT NULL DROP TABLE Categories")

In [37]:
cursor.execute("""
    CREATE TABLE Categories(
        category_id INT PRIMARY KEY NOT NULL,
        pizza_category NVARCHAR(50)
    );
    """)

In [38]:
cursor.execute("IF OBJECT_ID('Sizes') IS NOT NULL DROP TABLE Sizes")

In [39]:
cursor.execute("""
    CREATE TABLE Sizes(
        size_id INT PRIMARY KEY NOT NULL,
        pizza_size NVARCHAR(10),
        size_to_n_people INT
    );
    """)

In [40]:
cursor.execute("IF OBJECT_ID('Pizzas') IS NOT NULL DROP TABLE Pizzas")

In [41]:
cursor.execute("""
    CREATE TABLE Pizzas(
        pizza_id INT PRIMARY KEY NOT NULL,
        pizza_name NVARCHAR(50),
        pizza_name_short NVARCHAR(50),
        unit_price DECIMAL(10,2),
        pizza_ingredients VARCHAR(200),
        category_id INT,
        size_id INT
    );
    """)

In [42]:
cursor.execute("IF OBJECT_ID('Lines') IS NOT NULL DROP TABLE Lines")

In [43]:
cursor.execute("""
    CREATE TABLE Lines(
        line_id INT PRIMARY KEY NOT NULL,
        order_id INT,
        quantity INT,
        total_price_line DECIMAL(10,2),
        pizza_id INT
    );
    """)

In [44]:
cursor.execute("IF OBJECT_ID('Orders') IS NOT NULL DROP TABLE Orders")

In [45]:
cursor.execute("""
    CREATE TABLE Orders(
        order_id INT PRIMARY KEY NOT NULL,
        order_date DATE,
        order_time TIME(0),
        price_order DECIMAL(10,2)
    );
    """)

In [46]:
cursor.close()

## FKs

In [47]:
cursor = conn.cursor()

In [48]:
cursor.execute("""
               ALTER TABLE Pizzas
               ADD CONSTRAINT FK_Pizzas_Categories
               FOREIGN KEY (category_id) REFERENCES Categories (category_id);
               """)

In [49]:
cursor.execute("""
               ALTER TABLE Pizzas
               ADD CONSTRAINT FK_Pizzas_Sizes
               FOREIGN KEY (size_id) REFERENCES Sizes (size_id);
               """)

In [50]:
cursor.execute("""
               ALTER TABLE Lines
               ADD CONSTRAINT FK_Lines_Orders
               FOREIGN KEY (order_id) REFERENCES Orders (order_id);
               """)

In [51]:
cursor.execute("""
               ALTER TABLE Lines
               ADD CONSTRAINT FK_Lines_Pizzas
               FOREIGN KEY (pizza_id) REFERENCES Pizzas (pizza_id);
               """)

# Data upload

In [54]:
cursor = conn.cursor()

for index, row in df_category.iterrows():
    cursor.execute("""
    INSERT INTO Categories (category_id, pizza_category)
    VALUES (?, ?)
    """, (row['category_id'], row['pizza_category']))

conn.commit()
cursor.close()

print("Datos insertados exitosamente.")

Datos insertados exitosamente.

In [58]:
cursor = conn.cursor()

for index, row in df_sizes.iterrows():
    cursor.execute("""
                   INSERT INTO Sizes (size_id, pizza_size, size_to_n_people)
                   VALUES (?, ?, ?)
                   """,
                   (row['size_id'], row['pizza_size'], row['size_to_n_people'])
                   )

conn.commit()
cursor.close()

print("Datos insertados exitosamente.")

Datos insertados exitosamente.

In [60]:
cursor = conn.cursor()

for index, row in df_pizza.iterrows():
    cursor.execute("""
                   INSERT INTO Pizzas (pizza_id, pizza_name, pizza_name_short, unit_price, pizza_ingredients, category_id, size_id)
                   VALUES (?, ?, ?, ?, ?, ?, ?)
                   """,
                   (row['pizza_id'], row['pizza_name'], row['pizza_name_short'], row['unit_price'], row['pizza_ingredients'], row['category_id'], row['size_id'])
                   )

conn.commit()
cursor.close()

print("Datos insertados exitosamente.")

Datos insertados exitosamente.

In [63]:
df_orders.columns

Index(['order_id', 'order_date', 'order_time', 'price_order'], dtype='object')

In [64]:
cursor = conn.cursor()

for index, row in df_orders.iterrows():
    cursor.execute("""
                   INSERT INTO Orders (order_id, order_date, order_time, price_order)
                   VALUES (?, ?, ?, ?)
                   """,
                   (row['order_id'], row['order_date'], row['order_time'], row['price_order'])
                   )

conn.commit()
cursor.close()

print("Datos insertados exitosamente.")

Datos insertados exitosamente.

In [61]:
df_line.columns

Index(['line_id', 'order_id', 'quantity', 'total_price_line', 'pizza_id'], dtype='object')

In [65]:
cursor = conn.cursor()

for index, row in df_line.iterrows():
    cursor.execute("""
                   INSERT INTO Lines (line_id, order_id, quantity, total_price_line, pizza_id)
                   VALUES (?, ?, ?, ?, ?)
                   """,
                   (row['line_id'], row['order_id'], row['quantity'], row['total_price_line'], row['pizza_id'])
                   )

conn.commit()
cursor.close()

print("Datos insertados exitosamente.")

Datos insertados exitosamente.